version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: reserva_equipos_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: luisfcx
      POSTGRES_USER: luisfc
      POSTGRES_PASSWORD: lafc3367
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reserva_equipos_backend
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reserva_equipos_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL=http://localhost:3000/api
    ports:
      - "4173:4173"
    networks:
      - app-network
    volumes:
      - ./frontend:/app

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
