version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: luisfcx
      POSTGRES_USER: luisfc
      POSTGRES_PASSWORD: lafc3367
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      HOST: db
      DATABASE: luisfcx
      DB_USERNAME: luisfc
      PASSWORD: lafc3367
      ACCESS_TOKEN_SECRET: equisdeequisde
      cookieKey: dobleequisde
    

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://192.168.0.9:3001
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
